# 1. Create a 3x3x3 array with random values.

In [1]:
import numpy as np

In [8]:
random_array = np.random.random((3, 3))

print(random_array)

[[0.37371635 0.94589619 0.11328082]
 [0.1237313  0.34333272 0.69814741]
 [0.52531488 0.41785842 0.14676334]]


# 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [9]:
matrix = np.zeros((5, 5))  # Create a 5x5 matrix filled with zeros

np.fill_diagonal(matrix[1:], [1, 2, 3, 4])  # Set values 1, 2, 3, 4 just below the diagonal

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3. Create a 8x8 matrix and fill it with a checkboard pattern.

In [10]:
matrix = np.zeros((8, 8), dtype=int)  # Create an 8x8 matrix filled with zeros

# Set the even rows and even columns to 1
matrix[::2, ::2] = 1    
matrix[1::2, 1::2] = 1

print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 4. Normalize a 5x5 random matrix.

In [14]:
# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Normalize the matrix
mean = np.mean(random_matrix)
std = np.std(random_matrix)
normalized_matrix = (random_matrix - mean) / std

print("Original Random Matrix:")
print(random_matrix)

print("\nNormalized Matrix:")
print(normalized_matrix)

Original Random Matrix:
[[0.99058557 0.37273548 0.99696853 0.47779262 0.28885811]
 [0.7045576  0.26714648 0.70507662 0.96745211 0.72811845]
 [0.28089075 0.87568349 0.5974369  0.93680918 0.10106714]
 [0.80915962 0.26099557 0.25014783 0.99777716 0.61809808]
 [0.25285922 0.86928807 0.00679888 0.45104351 0.51003982]]

Normalized Matrix:
[[ 1.3795065  -0.66009247  1.40057745 -0.31328596 -0.93698197]
 [ 0.43529306 -1.00865473  0.43700643  1.30314012  0.51307032]
 [-0.96328321  1.00020064  0.08167448  1.20198403 -1.55690302]
 [ 0.78059719 -1.02895963 -1.06476934  1.40324684  0.14987957]
 [-1.05581872  0.97908857 -1.86809412 -0.40158806 -0.20683398]]


# 5. How to find common values between two array?

In [16]:
# Create two NumPy arrays
array1 = np.array([11, 22, 33, 44, 55])
array2 = np.array([33, 44, 55, 66, 77])

# Find the common values between the two arrays
common_values = np.intersect1d(array1, array2)

print("Common Values:", common_values)

Common Values: [33 44 55]


# 6. How to get the dates of yesterday, today and tomorrow?

In [19]:
todays_date = np.datetime64('today', 'D')
print("Today's Date: ", todays_date)

yesterdays_date = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday's Date: ", yesterdays_date)

tomorrows_date = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's Date: ", tomorrows_date)

Today's Date:  2023-09-21
Yesterday's Date:  2023-09-20
Tomorrow's Date:  2023-09-22


# 7. Consider two random array A and B, check if they are equal?

In [25]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
print(A)
print()
print(B)

[[0.57200418 0.30358467 0.67910025]
 [0.68682967 0.31776491 0.4061798 ]
 [0.03471906 0.5631077  0.44419911]]

[[0.47876942 0.23997014 0.89343285]
 [0.23203875 0.40981236 0.97891198]
 [0.81001921 0.97585839 0.04671441]]


In [26]:
check_equal = np.array_equal(A, B) # Check if A and B are equal element-wise

if check_equal:
    print("A and B are equal.")
else:
    print("A and B are not equal.")

A and B are not equal.


# 8. Create random vector size of 10 and replace the maximum value by 0.

In [28]:
# Create a random vector of size 10
random_vector = np.random.rand(10)
print(random_vector)

[0.37692984 0.67408528 0.61311239 0.79877892 0.88548122 0.74925414
 0.80176291 0.46756915 0.83461549 0.93089749]


In [29]:
# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random Vector with Maximum Value Replaced:")
print(random_vector)

Random Vector with Maximum Value Replaced:
[0.37692984 0.67408528 0.61311239 0.79877892 0.88548122 0.74925414
 0.80176291 0.46756915 0.83461549 0.        ]


# 9. How to print all the values of an array?

In [41]:
# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Print all values in the array
print(my_array)

[1 2 3 4 5]


# 10. Subtract the mean of each row of a matrix.

In [33]:
# Create a sample matrix (3x3)
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Calculate the row-wise means
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from each row
normalized_matrix = matrix - row_means

print("Original Matrix:")
print(matrix)

print("\nMatrix with Row Means Subtracted:")
print(normalized_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11. Consider a given vector, how to add 1 to each element indexed by a second vector(be carefull with repeated indices)

In [44]:
V = np.ones(10)
I = np.random.randint(0,len(Z),20)
V += np.bincount(I, minlength=len(Z))
print(V)

[2. 2. 7. 3. 2. 5. 1. 2. 3. 3.]


# 12. How to get diagonal of a dot product?

In [46]:
# Create two matrices
matrix_A = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
matrix_B = np.array([[99, 88, 77], [66, 55, 44], [33, 22, 11]])

print(matrix_A)
print()
print(matrix_B)

[[11 22 33]
 [44 55 66]
 [77 88 99]]

[[99 88 77]
 [66 55 44]
 [33 22 11]]


In [47]:
# Compute the dot product
dot_product = np.dot(matrix_A, matrix_B)

# Extract the diagonal elements
diagonal = np.diag(dot_product)

# Print the diagonal elements
print(diagonal)

[ 3630  8349 10890]


# 13. How to find a most frequent value in an array?

In [51]:
my_array = np.random.randint(0,10,50)
print(my_array)

[7 0 5 8 3 8 1 5 6 9 0 5 4 7 2 4 2 3 8 3 7 7 1 5 7 3 6 8 9 9 1 9 1 5 0 0 1
 8 6 2 3 7 6 0 0 6 2 8 7 5]


In [52]:
# Find the most frequent value
most_frequent_value = np.bincount(my_array).argmax()

print("Most frequent value:", most_frequent_value)

Most frequent value: 7


# 14. How to get the n largest value of an array?

In [54]:
# Create a NumPy array
my_array = np.array([39, 13, 54, 61, 25, 97, 25, 67, 45, 73, 45])

# Specify the value of n (e.g., 3 largest values)
n = 3

# Use np.partition to get the n largest values
n_largest_values = np.partition(my_array, -n)[-n:]

print(f"{n} largest values:", n_largest_values)

3 largest values: [67 73 97]


# 15. How to create a record array from a regular array?

In [65]:
Z = np.array([("Hello", "Patel", 100),
              ("World", "Ankit", 201)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, S8, i8')

print(Z)
print()
print(R)

[['Hello' 'Patel' '100']
 ['World' 'Ankit' '201']]

[(b'Hello', b'Patel', 100) (b'World', b'Ankit', 201)]


# 16. How to swap two rows of an array?

In [69]:
# Create a NumPy array
my_array = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print("Array Before swapping:\n", my_array)

# Define the row numbers to swap
row1 = 0  # Index of the first row
row2 = 2  # Index of the second row

# Swap the rows
my_array[row1], my_array[row2] = my_array[row2].copy(), my_array[row1].copy()

# Print the array after swapping
print("Array after swapping rows:")
print(my_array)

Array Before swapping:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after swapping rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 17. Write a python code to reshape to the next dimension of numpy array.

In [70]:
# Create a 1D NumPy array
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape to the next dimension (2D)
arr_2d = arr_1d.reshape((2, -1))  # -1 automatically calculates the size of the second dimension

# Print the original and reshaped arrays
print("Original 1D Array:")
print(arr_1d)

print("\nReshaped 2D Array:")
print(arr_2d)


Original 1D Array:
[1 2 3 4 5 6]

Reshaped 2D Array:
[[1 2 3]
 [4 5 6]]
